### ISSUE TITLE
About iterations

### ISSUE THREAD

**Issue by Yanqiaosen** [xxhu94/GAT-COBO#1]
The number of iterations of the two data sets is 15 and 1 respectively, does it mean that the model converges under a small number of iterations? I tried to change the number of iterations, but the evaluation index of the model is still slowly improving, I don't quite understand why the number of iterations you set is so set.

**Comment by xxhu94** [comment]
In our experiments, we tested the operation of the model under various iteration number settings. 15 and 1 are just default settings that we think work well. You can change them to other values.
